### ISSUE TITLE
When I trying to run get_start.ipynb, I found some functions of factorizer can not be found.

### ISSUE THREAD

**Issue by yibingchen2023** [pashtari/factorizer-isles22#1]
There are no "ft.ReadImaged(["image", "label"], ensure_channel_first=True)" and "ft.load_properties(data_properties)".

**Comment by pashtari** [comment]
Hi! Thank you for pointing that out. This repository was initially compatible with the first version of `factorizer`, which included the Lightning data modules and transforms for ISELS'22. Over time, to streamline `factorizer`, I've removed some of the data modules and transforms in the more recent versions. To resolve the current issue, I've updated the requirement.txt to specifically use `factorizer v0.0.1`. `ft.ReadImaged` and `ft.load_properties` should work now.

Alternatively, you can also use the latest version of `factorizer`, but you need to implement your own data modules, training, and test loops.

**Comment by yibingchen2023** [comment]
Thanks a lot. The two suggestions are good, and I want to try them all.

**Comment by yibingchen2023** [comment]
Thanks a lot. The two suggestions are good, and I want to try them all.
